### PR TITLE
Fix #124: Center the header's title

### LINKED ISSUE #124: [Feature] Allow to center title
Currently, the title in `body.header` can't be centered, it should be.

In the `JasonViewActivity`, we should add a `TextView` for the title instead of relying on `toolbar.setTitle`.

### PR DESCRIPTION
**Pull request by realitix**
To proceed, we override the Toolbar class by adding a TextView for the
title. It works like the Toolbar but it gives us full control over the TextView.

### CODE REVIEW

**Comment by realitix** [comment]
title_centered

Nice !

**Comment by gliechtenstein** [comment]
How about if we do this?

- Keep the current system as is: The default align follows the system's default align
- Add additional options to advanced header title styling http://docs.jasonette.com/document/#advanced-title

Here's how it would work

```
...
  "header": {
    "title": {
      "type": "label",
      "text": "Title",
      "style": {
        "align": "center"
      }
    }
  }
...
```

Maybe we can allow `left` and `center` (or even `right` if it's feasible. I know they're feasible on iOS)

Here's an example: https://jasonbase.com/things/KdqV

**Comment by realitix** [comment]
Hello @gliechtenstein, I'm totally fine with that. I think it's a perfect solution. :+1: :100: 
If we don't specify alignment, on Android it will be at left and on ios at center.

I'm going to update my pull request to take that into account.
Can you do the ios counterpart @gliechtenstein because I can't sadly :disappointed: 
Like you can see on my github profil, Free software is the key :laughing:

**Comment by gliechtenstein** [comment]
@realitix Yup. I'll work on the iOS part. Thanks!

**Comment by gliechtenstein** [comment]
BTW is this easy to do for images as well? I think currently the image title automatically gets center aligned by default.

I'm thinking something like:

```
"title": {
  "type": "image",
  "url": "...",
  "style": {
    "align": "left"
  }
```

**Comment by realitix** [comment]
I'm starting with the title and I will do the image after. It shouldn't be too long.

**Comment by gliechtenstein** [comment]
awesome 👍

**Comment by gliechtenstein** [comment]
@realitix Just finished the iOS part, I went a bit overboard and added a bit more, including font, size, top, and left https://github.com/Jasonette/JASONETTE-iOS/pull/247

**Comment by realitix** [comment]
@gliechtenstein You are faster than me ! :1st_place_medal: 
I will do it on monday!

**Comment by realitix** [comment]
Almost done @gliechtenstein, I'm on my way to Australia, 24h to spend on plane... So I will update the pull request during the week!

**Comment by realitix** [comment]
I added support for `align`, `left`, `right`, `top`, `size`.

I still have `font` to add and `size` is not taken into account although it should.

Do you want to add the `right` alignment ?

**Comment by gliechtenstein** [comment]
@realitix nice!, I actually tried adding right alignment but it didn't really make sense and introduced some technical issues so just left it out. I think we can do without `right`.

**Comment by realitix** [comment]
Hello @gliechtenstein, it should be good now.
I removed the right alignment and size and font work well.

**Comment by gliechtenstein** [comment]
@realitix could you make sure this works with all the test cases over at https://github.com/Jasonette/JASONETTE-iOS/pull/247#issue-246472484 ? I have just tested and some of them don't seem to work.

**Comment by realitix** [comment]
Hello @gliechtenstein, indeed some examples are not working because of the top offset.
Can you explain me how you manage it in the IOs- counterpart. I think we are not using the same algorithm (this should be more detailed in the documentation when it will be merged).

**Comment by gliechtenstein** [comment]
@realitix it should work the same way as label type titles, I thought the whole point of this issue was to support "align: left"...

This is what I get when I open https://jasonbase.com/things/gXe7 : 

screenshot_20170816-102908


BTW did you close this issue by mistake? I do hope we can merge this in, it's just the image title doesn't work the same way the labels do.

**Comment by realitix** [comment]
Sorry for the closing. Indeed it's a mistake.

**Comment by realitix** [comment]
Hi @gliechtenstein, I worked only on the label part, that's why images are not working. I'm going to add image support soon. Like you can see, I am slow recently, it's because I'm in holidays in Australia until September. :wink: I will be faster then.

**Comment by gliechtenstein** [comment]
@realitix no worries :) no rush, please feel free to contribute at your own pace. You should enjoy your holidays!

**Comment by realitix** [comment]
Hello @gliechtenstein.
I updated the pull request to make it work with image too.
It feels strange that the label is left aligned (by default) on Android because the logo is center aligned (by default). It's not a big problem but some people could wonder why they need to explicitly set "align: 'center'" only for the label on Android.

I wait for your test ! :wink:

**Comment by gliechtenstein** [comment]
@realitix I made some fixes as well as setting the align to center by default as per your suggestion, and sent a pull request to your repo https://github.com/realitix/JASONETTE-Android/pull/1 I'll accept your PR here once you accept that PR to your repo.

**Comment by realitix** [comment]
Nice!

**Comment by gliechtenstein** [comment]
Thanks @realitix we finally made it :)

Here's the updated documentation http://docs.jasonette.com/document/#advanced-title

**Pull request merged**
