### PR TITLE
Fix #127 Background image is no more displayed

### LINKED ISSUE #127: Background image is no more loaded
I have rebased on develop branch and with my last pull request, background no more show up (whereas it's a gif or jpg).

I'm fixing it.

### PR DESCRIPTION
**Pull request by realitix**
Background of sectionLayout should always be transparent.

As soon as the image is loaded, I set the background as transparent.

### CODE REVIEW

**Comment by realitix** [comment]
See the #127 issue

**Comment by gliechtenstein** [comment]
I think I took it out while working on the new status screens `loading.json` and `error.json` because there were some issues. But unfortunately I can't remember what it was!

I do remember going through a lot of trial and error for this, so will need to go back and check all the edge cases. 

Can you share a isolated test case where you can see this problem very clearly? That would help me understand the problem better, and also it would be useful for future reference even after we merge and close this. Thanks!

**Comment by realitix** [comment]
If you put Jasonette on last commit on develop branch, you cannot put an image as background anymore.

You can try with your jasonette: https://jasonbase.com/things/o2Kw

**Comment by gliechtenstein** [comment]
@realitix Just merged! It's great that this fix doesn't affect the rest, I will make sure to go back and check all the edge cases and see if things don't break if I add back the transparent background when I get time, but for now looks like the image is working! 🌈

**Pull request merged**
