### PR TITLE
add $convert.csv feature for #18

### PR DESCRIPTION
**Pull request by brad**
This adds support for [CSV converting](https://jasonette.github.io/documentation/actions/#convertcsv) to Android. @gliechtenstein I didn't really know what I was doing here, just started playing with Jasonette. As such, I would appreciate any guidance if this isn't up to snuff. It does work on the Jasonpedia example. If I can get this merged in, I will happily make a PR for RSS support as well :wink: :santa:

### CODE REVIEW

**Comment by lukeramsden** [comment]
Have you tried testing it with things other than Jasonpedia? Also, what happens if you pass it invalid CSV?

**Comment by gliechtenstein** [comment]
@lukeramsden I think if it works with Jasonpedia it should work other CSV types, since this `$convert.csv` is just a simple "interface" action that calls another library. But I agree it would be nice to make sure it works with different test cases. @brad I would appreciate it if you could test a few more test cases and let us know (Maybe you could even add some more test cases to Jasonpedia itself)

---

That said,,, @brad Wow thanks for figuring this out and making it work. 

I have a good news, and a bad news, and another good news.

Good news:  Yes you pretty much nailed it, this is how it works. I would totally appreciate it if you could also add RSS support as well!

Now for the bad news: For various reasons, I've been actually working on switching out the JS engine. It works but I haven't merged this in yet because I wanted to test some more. You can find the branch here https://github.com/Jasonette/JASONETTE-Android/tree/J2V8  It is very very likely that we will merge this in after completely confirming that it works, which means we will need a re-write of the convert.csv logic here to go with the new engine.

However, lastly for the good news again: Switching out the JS engine to J2V8 reduces the APK size down to around 9MB (Used to be like 40MB) with room for more, and solves a lot of other problems, which is a great news. And since it looks like you understand how this works, I'm guessing you won't have much trouble porting both the CSV version and RSS version to work with the new engine.

So,, would you like to take a stab at this one more time from the new branch? Basically you just need to pull from https://github.com/Jasonette/JASONETTE-Android/tree/J2V8 and rewrite the csv convert part just like you did here to match the new engine. It's not so much different from the previous approach since they're both JS engines. And maybe once you're done we can merge all of this into the master branch altogether. What do you think?

**Comment by brad** [comment]
@lukeramsden Thanks for the suggestions. Looking at it a bit closer, it looks like I should do something like `JasonHelper.next("error", action, error, context);` when there is invalid CSS. And thank you for suggesting I try different CSV files. The next one I tried wouldn't parse successfully, so I'll see if I can figure out why, and possibly make another example on Jasonpedia for it.

@gliechtenstein That sounds great! I'll take a look at making this work on the J2V8 branch.

**Comment by brad** [comment]
Fixed in #20

**Pull request closed without merging**
