### PR TITLE
add $convert.csv feature for #18

### PR DESCRIPTION
**Pull request by brad**
This is the J2V8 version of #19 with added error handling. I did manage to find a CSV where the parser fails, but I suspect it is not an Android specific error because the error happens within the Javascript function. I get an error when there are quotes in a field that have been escaped by doubling up the double quotes, which some CSV writers do. Here is a minimal example:
```csv
"testid","contentwithhtml"
1,"testing a <a href=""http://google.com"">link</a>"
```

I had to use the runtime to run additional javascript to `JSON.stringify` the data. I couldn't see any other way to properly convert it to a string. `toString` resulted in something like `[[object], [object], [object]...]`

### CODE REVIEW

**Comment by gliechtenstein** [comment]
@brad Yup this works! Just tested. For now I think we should drop the edge case like the one you mentioned. It looks like it's going to be a lot of headache and a lot of messy hacks to make this work and I don't think it's worth it. I've tested with a couple of normal cases and they all work so I think we're good to go.

**Comment by gliechtenstein** [comment]
Merged 🚀

**Comment by gliechtenstein** [comment]
@brad let me know if you're going to be working on the RSS version as well. Also please let me know if you run into any problem with other parts of this branch, still testing! Hoping to merge this in soon  :)

**Comment by brad** [comment]
Thanks @gliechtenstein :+1: Yes, I will do the RSS conversion now. I'll let you know if I find any other issues in the branch. You can @ me on Slack too (@bradpitcher)

**Pull request merged**
