### PR TITLE
Add Camera support in background (see #78)

### PR DESCRIPTION
**Pull request by realitix**
You all waited it... Here the pull request !! :wink: 
You can already try it, but I will do refactoring to improve the code.

@gliechtenstein look forward that you test it!

### CODE REVIEW

**Comment by gliechtenstein** [comment]
Wow that was fast, this is awesome! 

I added back the camera background demo on Jasonpedia to test these out https://github.com/Jasonette/Jasonpedia/commit/4029b80416310420e1fc617b15447d6c1a29ce2d

BTW I found one bug. When you test with the Jasonpedia example, you switch back and forth between different backgrounds https://raw.githubusercontent.com/Jasonette/Jasonpedia/gh-pages/view/background/index.json

And looks like the code skips the camera front/back mode setting when it's already initialized. You can try by pressing the `camera` button first, and then `mirror` to get the other side of the camera. The first time it will load fine, but the second time it will end up with a white blank screen. Could you take a look at this? Other than this it looks amazing!

**Comment by gliechtenstein** [comment]
A couple of other camera based demos you can try out, just for reference:

- http://docs.jasonette.com/examples/#weather
- https://raw.githubusercontent.com/Jasonette/Jasonpedia/gh-pages/view/layer/pokemon/index.json

**Comment by gliechtenstein** [comment]
@realitix just in case you missed my previous comments, could you take a look at the bug? would love to merge this in.

**Comment by realitix** [comment]
Don't worry @gliechtenstein, I know this pull request is important and didn't miss your message. It's just that I wait for the pull request #136 to be merged, there is a dependency.

**Comment by gliechtenstein** [comment]
@realitix i see! Just merged it! 🚀 https://github.com/Jasonette/JASONETTE-Android/pull/136#event-1165322509

**Comment by realitix** [comment]
From what I see in this example (https://raw.githubusercontent.com/Jasonette/Jasonpedia/gh-pages/view/background/index.json), the mirror camera must be the default one. I was doing the contrary. OK

**Comment by realitix** [comment]
No!  :cry: I fucked up the commit history...
I have to recreate it.

**Comment by realitix** [comment]
I resolved the history problem, my repository was no more synchronized, I don't know why... To resolve it, I add to do a `push --force` to rewrite the commit log. It can do some strange things on your local repository. So if you can do `git fetch origin pull/132/head:realitix_add_camera`, the `realitix_add_camera` local branch will be fine.

Apart from that, I noticed that the screenshot is shared with black screen when camera is selected.

**Comment by realitix** [comment]
I tried with this example: http://docs.jasonette.com/examples/#weather
It's not working but it's another bug because the view is never loaded. On android, it seems that `head` must contain a `data` attribute to parse the `templates` attribute.

**Comment by gliechtenstein** [comment]
@realitix hmm that's weird, that shouldn't happen. The way it should work is:

1. If head.data AND head.templates.body exists, it automatically renders
2. If head.templates.body exists but no head.data, then it waits until a `$render` action is explicitly called.

In this case the `$load` event triggers `draw` action which eventually calls `$render` so it should trigger the render theoretically.

I am unable to test out with android studio at the moment but will test it out as soon as i can and report back, hopefully tomorrow!

**Comment by realitix** [comment]
@gliechtenstein I didn't know that, I will put a breakpoint in the onLoad function.

**Comment by gliechtenstein** [comment]
@realitix I just checked and looks like the weather app is working fine

screenshot_20170718-143142

But I've found a different bug. 

## Bug

To replicate, you can 

1. Open the background demo app from Jasonpedia https://raw.githubusercontent.com/Jasonette/Jasonpedia/gh-pages/view/background/index.json 
2. tap "cat" => it will display an image
3. now tap "camera" => doesn't work

## What works

But it works if you go straight to camera

1. Open the background demo app from Jasonpedia https://raw.githubusercontent.com/Jasonette/Jasonpedia/gh-pages/view/background/index.json 
2. tap "Camera"
3. It works

**Comment by realitix** [comment]
Hello @gliechtenstein.

Strange, this morning, the weather APP is not locked on the loading screen but I saw a new bug, maybe you will know what it could be.
It seems that the template is not interpreted (see screenshot).
screenshot_20170719-070535

**Comment by realitix** [comment]
I updated, it works well now! For the bug I showed, maybe we could open another issue because it's not related to the camera background.

**Comment by gliechtenstein** [comment]
@realitix Now I can't get the `mirror` to work. Can you please test out all the cases to make sure all of them work?

**Comment by realitix** [comment]
It's strange @gliechtenstein. Before pushing, I tested everything and it worked, let me test again.

**Comment by gliechtenstein** [comment]
@realitix looks like my camera is messed up (I dropped it and looks like the front camera is gone), sorry about the confusion!

**Comment by gliechtenstein** [comment]
Merged! 💃🏻🦄

**Comment by gliechtenstein** [comment]
Added back the camera related documentation too http://docs.jasonette.com/document/#background :)

**Pull request merged**
